version: "3"

services:
  storage:
    image: storage:latest
    container_name: storage
    hostname: storage
    ports:
      - "8090:8090"
  receiver:
    image: receiver:latest
    container_name: receiver
    hostname: receiver
    ports:
      - "8080:8080"
    depends_on:
      - storage
  processing:
    image: processing:latest
    container_name: processing
    hostname: processing
    ports:
      - "8100:8100"
    networks:
      - host
    depends_on:
      - storage
  audit_log:
    image: audit_log:latest
    container_name: audit_log
    hostname: audit
    ports:
      - "8110:8110"
    depends_on:
      - storage

networks: host
