version: "6.1"

services:
  storage:
    container_name: storage
    image: ${pwd}/../storage
    hostname: storage
    ports:
      - "8090:8090"
  receiver:
    container_name: receiver
    image: ${pwd}/../receiver
    hostname: receiver
    ports:
      - "8080:8080"
    depends_on:
      - storage
  processing:
    container_name: processing
    image: ${pwd}/../processing
    hostname: processing
    ports:
      - "8100:8100"
    depends_on:
      - storage
  audit_log:
    container_name: audit_log
    image: ${pwd}/../audit_log
    hostname: audit
    ports:
      - "8110:8110"
    depends_on:
      - storage
