version: "6.1"

services:
  storage:
    container_name: storage
    build:
      context: ../
      dockerfile: ../storage
    hostname: storage
    ports:
      - "8090:8090"
    depends_on:
      - kafka
  receiver:
    container_name: receiver
    build:
      context: ../
      dockerfile: ../receiver
    hostname: receiver
    ports:
      - "8080:8080"
    depends_on:
      - storage
      - kafka
  processing:
    container_name: processing
    build:
      context: ../
      dockerfile: ../processing
      network: "host"
    hostname: processing
    ports:
      - "8100:8100"
    depends_on:
      - storage
      - kafka
  audit_log:
    container_name: audit_log
    build:
      context: ../
      dockerfile: ../audit_log
    hostname: audit
    ports:
      - "8110:8110"
    depends_on:
      - storage
      - kafka
