version: "6.1"

services:
  storage:
    container_name: storage
    build:
      context: ../
      dockerfile: ./storage/Dockerfile
    hostname: storage
    ports:
      - "8090:8090"
  receiver:
    container_name: receiver
    build:
      context: ../
      dockerfile: ./receiver/Dockerfile
    hostname: receiver
    ports:
      - "8080:8080"
    depends_on:
      - storage
  processing:
    container_name: processing
    build:
      context: ../
      dockerfile: ./processing/Dockerfile
    hostname: processing
    ports:
      - "8100:8100"
    depends_on:
      - storage
  audit_log:
    container_name: audit_log
    build:
      context: ../
      dockerfile: ./audit_log/Dockerfile
    hostname: audit
    ports:
      - "8110:8110"
    depends_on:
      - storage
